### ISSUE TITLE
Когда новая версия?

### ISSUE THREAD

**Issue by FililT1** [ma3rxofficial/ComputerCraft#5]
последний релиз вышел 24 августа, при этом репозиторий и программы ОС продолжают обновляться. 
когда все это будет выпущено отдельной версией?

**Comment by ma3rxofficial** [comment]
Готовлю. Как раз сейчас занимаюсь выпиливанием и улучшением программ, которые этого заслуживают.

**Comment by KaiserIIV** [comment]
мы все очень ждем =))

**Comment by ma3rxofficial** [comment]
А меня ебёт это как будто =))

**Comment by ma3rxofficial** [comment]
Мне похуй =))

**Comment by FililT1** [comment]
И ГДЕ БЛЯТЬ

**Comment by ma3rxofficial** [comment]
Пока не вышла. Да и в чём проблема обновлять проги с помощью Checker-a?

**Comment by FililT1** [comment]
Checker прекрасно работает, это да
НО ВЫПУСТИ СУКА НОВУЮ ВЕРСИЮ ПРОШУУУУ

**Comment by ma3rxofficial** [comment]
Попроси еще раз, может выпущу

**Comment by ma3rxofficial** [comment]
Выпустил.
