### ISSUE TITLE
Когда SpeedOS выйдет на дискеты?

### ISSUE THREAD

**Issue by FililT1** [ma3rxofficial/ComputerCraft#6]
когда?

**Comment by ma3rxofficial** [comment]
ДА НИКОГДА НАХУЙ

**Comment by ma3rxofficial** [comment]
А если серьёзно: может быть, но не скоро. Просто мне уже писали, что Pastebin и GitHub у кого-то не работает...

**Comment by ma3rxofficial** [comment]
Вопрос закрыт.

**Comment by FililT1** [comment]
СУКААААААААААААААААА
